@api = http://localhost:5000/v1.0
@foos = {{api}}/foos

GET {{foos}}

###

PUT {{foos}}
Content-Type: application/json
{
  "text": "my first fooo"
}

###

PATCH {{foos}}
Content-Type: application/json
{
  "id": "6d1e2dd5-ea75-45ec-9209-33473b59b272",
  "text": "updated"
}

###

Delete {{foos}}/6d1e2dd5-ea75-45ec-9209-33473b59b272