@api = http://localhost:5000/v1.0
@foos = {{api}}/foos

GET {{foos}}

###

PUT {{foos}}
Content-Type: application/json
{
  "text": "my first fooo"
}

###

PATCH {{foos}}
Content-Type: application/json
{
  "id": "bd7e1eb2-b4d6-4e3f-98c2-5b86a75cf136",
  "text": "updated"
}

###

Delete {{foos}}/bd7e1eb2-b4d6-4e3f-98c2-5b86a75cf136