@api = http://localhost:5000/v1.0
@foos = {{api}}/foos

GET {{foos}}

###

PUT {{foos}}
Content-Type: application/json
{
  "text": "my first fooo"
}

###

PATCH {{foos}}
Content-Type: application/json
{
  "id": "e266ff12-1ba9-4e09-91c2-ad600b168bfd",
  "text": "updated"
}

###

Delete {{foos}}/e266ff12-1ba9-4e09-91c2-ad600b168bfd